---
driver_plugin: digitalocean

driver_config:
  private_networking: false
  digitalocean_client_id: <%= ENV['DIGITALOCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITALOCEAN_API_KEY'] %>
  flavor_id: 63
  region_id: 4

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.0

suites:
  - name: pg-90
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_0]
  - name: pg-91
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_1]
  - name: pg-92
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_2]
  - name: pg-93
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_3]
