---
driver:
  name: digitalocean

driver_config:
  private_networking: false
  region: nyc3

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.1.2

platforms:
  - name: ubuntu-14-04-x64

suites:
  - name: pg-91
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_1]
  - name: pg-94
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_4]
