---
driver_plugin: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-12.04
    driver:
      box: express42/ubuntu12.04-chef11
  - name: ubuntu-14.04
    driver:
      box: express42/ubuntu-14.04
  - name: debian-6.0.9
  - name: debian-7.6

suites:
  - name: pg-90
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_0]
  - name: pg-91
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_1]
  - name: pg-92
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_2]
  - name: pg-93
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_3]
