---
driver:
  name: ec2
  access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  aws_ssh_key_id: travis-ci-aws
  security_group_ids: ["sg-66b16711"]
  region: eu-west-1
  require_chef_omnibus: 12
  instance_type: t1.micro
  tags:
    Name: travis-ci

transport:
  ssh_key: '.travis/travis-ci-aws.pem'
  connection_timeout: 10
  connection_retries: 5

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-5a60c229
    transport:
      username: ubuntu
  - name: ubuntu-16.04
    transport:
      username: ubuntu

provisioner:
  name: chef_solo

suites:
  - name: pg-91
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_1]
  - name: pg-94
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_4]
  - name: pg-94-chef11
    run_list:
      - recipe[apt]
      - recipe[pgtest::test_9_4]
    provisioner:
      name: chef_zero
      require_chef_omnibus: 11.14.2
