LineLength:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'
MethodLength:
  Exclude:
    - 'test/**/spec_helper.rb'
AbcSize:
  Exclude:
    - 'test/**/spec_helper.rb'
Documentation:
  Enabled: false
