language: ruby
cache: bundler
sudo: false
rvm:
- 2.1.5
bundler_args: --without kitchen_vagrant development
before_install:
- openssl aes-256-cbc -K $encrypted_f6f670865f61_key -iv $encrypted_f6f670865f61_iv -in .travis/secret_keys.tar.enc -out .travis/secret_keys.tar -d
- tar xf .travis/secret_keys.tar -C .travis
- mv .travis/travis ~/.ssh/id_rsa
script:
- bundle exec rubocop
- bundle exec foodcritic -f any .
- bundle exec rspec
- bundle exec kitchen test -c 10 -d always
deploy:
  edge: true
  provider: chef-supermarket
  user_id: express42
  client_key: ".travis/express42.pem"
  on:
    tags: true
notifications:
  flowdock: d4fbb65de6c9c868a2dfc4b38fbd34c1
env:
  global:
  - KITCHEN_YAML=.kitchen.cloud.yml
