language: ruby
cache: bundler
sudo: false
rvm:
- 2.0.0
bundler_args: "--without kitchen_vagrant development --path=~/.bundle"
before_install:
- openssl aes-256-cbc -K $encrypted_f6f670865f61_key -iv $encrypted_f6f670865f61_iv
  -in .travis/id_travis.enc -out ~/.ssh/id_rsa -d
script:
- bundle exec rubocop
- bundle exec foodcritic -f any .
- bundle exec rspec
- bundle exec kitchen test -c 10 -d always
notifications:
  flowdock: d4fbb65de6c9c868a2dfc4b38fbd34c1
env:
  global:
  - KITCHEN_YAML=.kitchen.cloud.yml
